# Generated by Django 4.0.3 on 2022-05-16 23:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=25)),
                ('contenido', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Autor', models.CharField(max_length=40)),
                ('Imagen', models.ImageField(upload_to='')),
                ('Fecha', models.DateTimeField()),
            ],
        ),
    ]
